"""add services domain

Revision ID: 5427d0420d0e
Revises: 8d38bfc82328
Create Date: 2026-09-22 14:38:09.322035

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5427d0420d0e"
down_revision: str | Sequence[str] | None = "8d38bfc82328"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "CERTIFICATES",
                "DOCUMENTS",
                "WELFARE",
                "EDUCATION",
                "HEALTHCARE",
                "AGRICULTURE",
                "EMPLOYMENT",
                "BUSINESS",
                "TRANSPORT",
                "MUNICIPAL",
                "REVENUE",
                "SOCIAL_SECURITY",
                "IDENTITY",
                "UTILITIES",
                "OTHER",
                name="service_category",
            ),
            nullable=False,
        ),
        sa.Column("service_type", sa.String(length=150), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column(
            "delivery_mode",
            sa.Enum("ONLINE", "OFFLINE", "BOTH", name="delivery_mode"),
            nullable=False,
        ),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column("official_service_url", sa.String(length=2048), nullable=True),
        sa.Column("application_url", sa.String(length=2048), nullable=True),
        sa.Column("fee_summary", sa.String(length=300), nullable=True),
        sa.Column("processing_time_summary", sa.String(length=300), nullable=True),
        sa.Column("location_summary", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="service_publication_status"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_category"), "services", ["category"], unique=False)
    op.create_index(op.f("ix_services_department_id"), "services", ["department_id"], unique=False)
    op.create_index(op.f("ix_services_district_id"), "services", ["district_id"], unique=False)
    op.create_index(op.f("ix_services_locale"), "services", ["locale"], unique=False)
    op.create_index(
        op.f("ix_services_organization_id"), "services", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_services_publication_status"), "services", ["publication_status"], unique=False
    )
    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)
    op.create_index(op.f("ix_services_source_id"), "services", ["source_id"], unique=False)
    op.create_index(op.f("ix_services_state_id"), "services", ["state_id"], unique=False)
    op.create_index(op.f("ix_services_status"), "services", ["status"], unique=False)
    op.create_index(
        op.f("ix_services_verification_status"), "services", ["verification_status"], unique=False
    )
    op.create_table(
        "service_application_methods",
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel_type",
            sa.Enum(
                "ONLINE",
                "OFFLINE",
                "MOBILE_APP",
                "MEESEVA",
                "DEPARTMENT_PORTAL",
                "SERVICE_CENTER",
                "IN_PERSON",
                "OTHER",
                name="application_channel_type",
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_application_methods_service_id"),
        "service_application_methods",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "service_required_documents",
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_required_documents_service_id"),
        "service_required_documents",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "service_requirements",
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column(
            "requirement_type",
            sa.Enum("AGE", "RESIDENCY", "INCOME", "OCCUPATION", "OTHER", name="requirement_type"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_value", sa.Integer(), nullable=True),
        sa.Column("max_value", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_requirements_service_id"),
        "service_requirements",
        ["service_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_requirements_service_id"), table_name="service_requirements")
    op.drop_table("service_requirements")
    op.drop_index(
        op.f("ix_service_required_documents_service_id"), table_name="service_required_documents"
    )
    op.drop_table("service_required_documents")
    op.drop_index(
        op.f("ix_service_application_methods_service_id"), table_name="service_application_methods"
    )
    op.drop_table("service_application_methods")
    op.drop_index(op.f("ix_services_verification_status"), table_name="services")
    op.drop_index(op.f("ix_services_status"), table_name="services")
    op.drop_index(op.f("ix_services_state_id"), table_name="services")
    op.drop_index(op.f("ix_services_source_id"), table_name="services")
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.drop_index(op.f("ix_services_publication_status"), table_name="services")
    op.drop_index(op.f("ix_services_organization_id"), table_name="services")
    op.drop_index(op.f("ix_services_locale"), table_name="services")
    op.drop_index(op.f("ix_services_district_id"), table_name="services")
    op.drop_index(op.f("ix_services_department_id"), table_name="services")
    op.drop_index(op.f("ix_services_category"), table_name="services")
    op.drop_table("services")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 874e41ffb818's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. Only the enums *first created*
    # here are dropped — `verification_status` is reused from
    # 874e41ffb818 via `postgresql.ENUM(..., create_type=False)` above
    # and must not be dropped while other tables still reference it.
    for enum_name in (
        "requirement_type",
        "application_channel_type",
        "service_publication_status",
        "delivery_mode",
        "service_category",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
