"""add search_documents

Revision ID: 5d30d9b37791
Revises: 874e41ffb818
Create Date: 2026-09-21 17:30:37.142819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d30d9b37791"
down_revision: str | Sequence[str] | None = "874e41ffb818"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not auto-generated, and required: the trigram GIN index below
    # needs gin_trgm_ops, which only exists once pg_trgm is enabled.
    # Every environment this runs against (local/staging/production)
    # starts without it — verified by hand against a fresh database.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_documents",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("searchable_text", sa.Text(), nullable=True),
        sa.Column("route", sa.String(length=500), nullable=False),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            # postgresql.ENUM (dialect-specific), not the generic
            # sa.Enum: verified by hand that create_type=False on the
            # generic sa.Enum does NOT suppress a CREATE TYPE attempt
            # here (Alembic's create_table still issues it, causing
            # "type already exists" on a downgrade-then-upgrade cycle),
            # while the dialect-specific ENUM's create_type is what
            # Alembic's DDL path actually honors — reuses the type
            # Phase 3's migration already created.
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type", "entity_id", "locale", name="uq_search_documents_entity_locale"
        ),
    )
    op.create_index(
        op.f("ix_search_documents_category"), "search_documents", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_district_id"), "search_documents", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_entity_id"), "search_documents", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_entity_type"), "search_documents", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_locale"), "search_documents", ["locale"], unique=False
    )
    op.create_index(
        "ix_search_documents_search_vector",
        "search_documents",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_search_documents_source_id"), "search_documents", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_state_id"), "search_documents", ["state_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_documents_status"), "search_documents", ["status"], unique=False
    )
    op.create_index(
        "ix_search_documents_title_trgm",
        "search_documents",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_search_documents_title_trgm",
        table_name="search_documents",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_search_documents_status"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_state_id"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_source_id"), table_name="search_documents")
    op.drop_index(
        "ix_search_documents_search_vector", table_name="search_documents", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_search_documents_locale"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_entity_type"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_entity_id"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_district_id"), table_name="search_documents")
    op.drop_index(op.f("ix_search_documents_category"), table_name="search_documents")
    op.drop_table("search_documents")
    # ### end Alembic commands ###

    # Deliberately NOT dropping the pg_trgm extension here: unlike the
    # narrow, column-specific enum types Phase 3's migration had to
    # clean up, an extension is generic, reusable infrastructure a later
    # migration may also depend on — dropping it on this table's removal
    # would be a surprising, unrelated side effect for whoever downgrades
    # this specific migration.
