"""initial schema: geography, provenance, users

Revision ID: 874e41ffb818
Revises:
Create Date: 2026-09-21 14:29:41.956538

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "874e41ffb818"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("organization", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column("retrieved_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "states",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "PLANNED", name="state_status"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_states_slug"), "states", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Enum("USER", "EDITOR", "ADMIN", name="user_role"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "districts",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_id", "code", name="uq_districts_state_code"),
        sa.UniqueConstraint("state_id", "slug", name="uq_districts_state_slug"),
    )
    op.create_index(op.f("ix_districts_state_id"), "districts", ["state_id"], unique=False)
    op.create_table(
        "source_versions",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("snapshot_ref", sa.String(length=500), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_versions_source_id"), "source_versions", ["source_id"], unique=False
    )
    op.create_table(
        "verification_records",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED", "NEEDS_REVIEW", "EXPIRED", "UNVERIFIED", name="verification_status"
            ),
            nullable=False,
        ),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_records_entity_id"),
        "verification_records",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_records_entity_type"),
        "verification_records",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_records_source_id"),
        "verification_records",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_records_status"), "verification_records", ["status"], unique=False
    )
    op.create_table(
        "change_records",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="change_review_status"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_version_id"], ["source_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_records_detected_at"), "change_records", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_change_records_entity_id"), "change_records", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_change_records_entity_type"), "change_records", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_change_records_review_status"), "change_records", ["review_status"], unique=False
    )
    op.create_index(
        op.f("ix_change_records_source_version_id"),
        "change_records",
        ["source_version_id"],
        unique=False,
    )
    op.create_table(
        "constituencies",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column(
            "type", sa.Enum("ASSEMBLY", "PARLIAMENTARY", name="constituency_type"), nullable=False
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=170), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_id", "type", "slug", name="uq_constituencies_state_type_slug"),
    )
    op.create_index(
        op.f("ix_constituencies_district_id"), "constituencies", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_constituencies_state_id"), "constituencies", ["state_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("qualification", sa.String(length=150), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_constituencies_state_id"), table_name="constituencies")
    op.drop_index(op.f("ix_constituencies_district_id"), table_name="constituencies")
    op.drop_table("constituencies")
    op.drop_index(op.f("ix_change_records_source_version_id"), table_name="change_records")
    op.drop_index(op.f("ix_change_records_review_status"), table_name="change_records")
    op.drop_index(op.f("ix_change_records_entity_type"), table_name="change_records")
    op.drop_index(op.f("ix_change_records_entity_id"), table_name="change_records")
    op.drop_index(op.f("ix_change_records_detected_at"), table_name="change_records")
    op.drop_table("change_records")
    op.drop_index(op.f("ix_verification_records_status"), table_name="verification_records")
    op.drop_index(op.f("ix_verification_records_source_id"), table_name="verification_records")
    op.drop_index(op.f("ix_verification_records_entity_type"), table_name="verification_records")
    op.drop_index(op.f("ix_verification_records_entity_id"), table_name="verification_records")
    op.drop_table("verification_records")
    op.drop_index(op.f("ix_source_versions_source_id"), table_name="source_versions")
    op.drop_table("source_versions")
    op.drop_index(op.f("ix_districts_state_id"), table_name="districts")
    op.drop_table("districts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_states_slug"), table_name="states")
    op.drop_table("states")
    op.drop_table("sources")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary: Alembic's autogenerate creates a
    # native Postgres ENUM TYPE alongside a column that uses sa.Enum(...),
    # but does not emit a matching DROP TYPE in the downgrade — a documented
    # Alembic limitation, verified here by running upgrade -> downgrade ->
    # upgrade, which fails with "type already exists" without this block.
    for enum_name in (
        "constituency_type",
        "change_review_status",
        "verification_status",
        "user_role",
        "state_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
