"""add schemes domain

Revision ID: 8b03ffd6bc96
Revises: 5427d0420d0e
Create Date: 2026-09-22 15:41:44.879781

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b03ffd6bc96"
down_revision: str | Sequence[str] | None = "5427d0420d0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schemes",
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "SCHOLARSHIP",
                "PENSION",
                "SUBSIDY",
                "FINANCIAL_ASSISTANCE",
                "INSURANCE",
                "HOUSING",
                "HEALTHCARE",
                "EDUCATION",
                "AGRICULTURE",
                "EMPLOYMENT",
                "SKILL_DEVELOPMENT",
                "WOMEN_CHILD_WELFARE",
                "SOCIAL_WELFARE",
                "BUSINESS_ENTREPRENEURSHIP",
                "DISABILITY_SUPPORT",
                "OTHER",
                name="scheme_category",
            ),
            nullable=False,
        ),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column("official_scheme_url", sa.String(length=2048), nullable=True),
        sa.Column("application_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="scheme_publication_status"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schemes_category"), "schemes", ["category"], unique=False)
    op.create_index(op.f("ix_schemes_department_id"), "schemes", ["department_id"], unique=False)
    op.create_index(op.f("ix_schemes_district_id"), "schemes", ["district_id"], unique=False)
    op.create_index(op.f("ix_schemes_locale"), "schemes", ["locale"], unique=False)
    op.create_index(
        op.f("ix_schemes_organization_id"), "schemes", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_schemes_publication_status"), "schemes", ["publication_status"], unique=False
    )
    op.create_index(op.f("ix_schemes_slug"), "schemes", ["slug"], unique=True)
    op.create_index(op.f("ix_schemes_source_id"), "schemes", ["source_id"], unique=False)
    op.create_index(op.f("ix_schemes_state_id"), "schemes", ["state_id"], unique=False)
    op.create_index(op.f("ix_schemes_status"), "schemes", ["status"], unique=False)
    op.create_index(
        op.f("ix_schemes_verification_status"), "schemes", ["verification_status"], unique=False
    )
    op.create_table(
        "scheme_application_methods",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel_type",
            postgresql.ENUM(
                "ONLINE",
                "OFFLINE",
                "MOBILE_APP",
                "MEESEVA",
                "DEPARTMENT_PORTAL",
                "SERVICE_CENTER",
                "IN_PERSON",
                "OTHER",
                name="application_channel_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheme_application_methods_scheme_id"),
        "scheme_application_methods",
        ["scheme_id"],
        unique=False,
    )
    op.create_table(
        "scheme_benefits",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column(
            "benefit_type",
            sa.Enum(
                "CASH_TRANSFER",
                "SUBSIDY",
                "SCHOLARSHIP_AMOUNT",
                "PENSION",
                "INSURANCE_COVERAGE",
                "LOAN_SUBSIDY",
                "IN_KIND_SUPPORT",
                "OTHER",
                name="benefit_type",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount_summary", sa.String(length=300), nullable=True),
        sa.Column("frequency_summary", sa.String(length=150), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheme_benefits_scheme_id"), "scheme_benefits", ["scheme_id"], unique=False
    )
    op.create_table(
        "scheme_related_services",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scheme_id", "service_id", name="uq_scheme_related_services_scheme_service"
        ),
    )
    op.create_index(
        op.f("ix_scheme_related_services_scheme_id"),
        "scheme_related_services",
        ["scheme_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheme_related_services_service_id"),
        "scheme_related_services",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "scheme_required_documents",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheme_required_documents_scheme_id"),
        "scheme_required_documents",
        ["scheme_id"],
        unique=False,
    )
    op.create_table(
        "scheme_requirements",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column(
            "requirement_type",
            postgresql.ENUM(
                "AGE",
                "RESIDENCY",
                "INCOME",
                "OCCUPATION",
                "OTHER",
                name="requirement_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_value", sa.Integer(), nullable=True),
        sa.Column("max_value", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheme_requirements_scheme_id"), "scheme_requirements", ["scheme_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheme_requirements_scheme_id"), table_name="scheme_requirements")
    op.drop_table("scheme_requirements")
    op.drop_index(
        op.f("ix_scheme_required_documents_scheme_id"), table_name="scheme_required_documents"
    )
    op.drop_table("scheme_required_documents")
    op.drop_index(
        op.f("ix_scheme_related_services_service_id"), table_name="scheme_related_services"
    )
    op.drop_index(
        op.f("ix_scheme_related_services_scheme_id"), table_name="scheme_related_services"
    )
    op.drop_table("scheme_related_services")
    op.drop_index(op.f("ix_scheme_benefits_scheme_id"), table_name="scheme_benefits")
    op.drop_table("scheme_benefits")
    op.drop_index(
        op.f("ix_scheme_application_methods_scheme_id"), table_name="scheme_application_methods"
    )
    op.drop_table("scheme_application_methods")
    op.drop_index(op.f("ix_schemes_verification_status"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_status"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_state_id"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_source_id"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_slug"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_publication_status"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_organization_id"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_locale"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_district_id"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_department_id"), table_name="schemes")
    op.drop_index(op.f("ix_schemes_category"), table_name="schemes")
    op.drop_table("schemes")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 5427d0420d0e's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. Only the enums *first created*
    # here are dropped — `requirement_type`/`application_channel_type`/
    # `verification_status` are reused via
    # `postgresql.ENUM(..., create_type=False)` above and must not be
    # dropped while Services' tables still reference them.
    for enum_name in ("benefit_type", "scheme_publication_status", "scheme_category"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
