"""add jobs domain

Revision ID: 8d38bfc82328
Revises: 5d30d9b37791
Create Date: 2026-09-22 10:09:03.783102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d38bfc82328"
down_revision: str | Sequence[str] | None = "5d30d9b37791"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "org_type",
            sa.Enum("CENTRAL", "STATE", "AUTONOMOUS_BODY", name="organization_type"),
            nullable=False,
        ),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("website_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_organizations_state_id"), "organizations", ["state_id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_departments_organization_name"),
    )
    op.create_index(
        op.f("ix_departments_organization_id"), "departments", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_departments_state_id"), "departments", ["state_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum("PERMANENT", "CONTRACT", "TEMPORARY", name="employment_type"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=150), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column("min_age", sa.Integer(), nullable=True),
        sa.Column("max_age", sa.Integer(), nullable=True),
        sa.Column("qualification_summary", sa.Text(), nullable=True),
        sa.Column("experience_summary", sa.Text(), nullable=True),
        sa.Column("salary_summary", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="job_publication_status"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_department_id"), "jobs", ["department_id"], unique=False)
    op.create_index(op.f("ix_jobs_district_id"), "jobs", ["district_id"], unique=False)
    op.create_index(op.f("ix_jobs_locale"), "jobs", ["locale"], unique=False)
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index(
        op.f("ix_jobs_publication_status"), "jobs", ["publication_status"], unique=False
    )
    op.create_index(op.f("ix_jobs_slug"), "jobs", ["slug"], unique=True)
    op.create_index(op.f("ix_jobs_source_id"), "jobs", ["source_id"], unique=False)
    op.create_index(op.f("ix_jobs_state_id"), "jobs", ["state_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_jobs_verification_status"), "jobs", ["verification_status"], unique=False
    )
    op.create_table(
        "job_notifications",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("notification_number", sa.String(length=150), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW",
                "PUBLISHED",
                "APPLICATION_OPEN",
                "APPLICATION_CLOSED",
                "EXAMINATION",
                "RESULT",
                "ARCHIVED",
                name="job_notification_status",
            ),
            nullable=False,
        ),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column("application_start", sa.Date(), nullable=True),
        sa.Column("application_end", sa.Date(), nullable=True),
        sa.Column("correction_window_end", sa.Date(), nullable=True),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column("total_vacancies", sa.Integer(), nullable=True),
        sa.Column("official_notification_url", sa.String(length=2048), nullable=True),
        sa.Column("official_application_url", sa.String(length=2048), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_notifications_job_id"), "job_notifications", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_notifications_source_id"), "job_notifications", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_notifications_status"), "job_notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_job_notifications_verification_status"),
        "job_notifications",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "job_vacancies",
        sa.Column("job_notification_id", sa.UUID(), nullable=False),
        sa.Column("post_name", sa.String(length=200), nullable=False),
        sa.Column("vacancy_count", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_notification_id"], ["job_notifications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_vacancies_job_notification_id"),
        "job_vacancies",
        ["job_notification_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_vacancies_job_notification_id"), table_name="job_vacancies")
    op.drop_table("job_vacancies")
    op.drop_index(op.f("ix_job_notifications_verification_status"), table_name="job_notifications")
    op.drop_index(op.f("ix_job_notifications_status"), table_name="job_notifications")
    op.drop_index(op.f("ix_job_notifications_source_id"), table_name="job_notifications")
    op.drop_index(op.f("ix_job_notifications_job_id"), table_name="job_notifications")
    op.drop_table("job_notifications")
    op.drop_index(op.f("ix_jobs_verification_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_state_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_slug"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_publication_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_locale"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_district_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_department_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_departments_state_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_organization_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_organizations_state_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 874e41ffb818's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. Only the enums *first created*
    # here are dropped — `verification_status` is reused from
    # 874e41ffb818 via `postgresql.ENUM(..., create_type=False)` above
    # and must not be dropped while other tables still reference it.
    for enum_name in (
        "job_notification_status",
        "job_publication_status",
        "employment_type",
        "organization_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
