"""add documents domain

Revision ID: 9ae6dce71bfa
Revises: f36a332eb8ca
Create Date: 2026-09-22 17:35:00.764133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ae6dce71bfa"
down_revision: str | Sequence[str] | None = "f36a332eb8ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "civic_documents",
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "document_type",
            sa.Enum(
                "CERTIFICATE",
                "IDENTITY_DOCUMENT",
                "RECORD",
                "PERMIT",
                "LICENSE",
                "REGISTRATION",
                "OTHER",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "PERSONAL",
                "IDENTITY",
                "RESIDENCE",
                "INCOME",
                "SOCIAL_CATEGORY",
                "EDUCATION",
                "BIRTH_DEATH",
                "DISABILITY",
                "LAND_REVENUE",
                "EMPLOYMENT",
                "BUSINESS",
                "FAMILY",
                "OTHER",
                name="document_category",
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("district_id", sa.UUID(), nullable=True),
        sa.Column(
            "delivery_mode",
            postgresql.ENUM("ONLINE", "OFFLINE", "BOTH", name="delivery_mode", create_type=False),
            nullable=False,
        ),
        sa.Column("official_document_url", sa.String(length=2048), nullable=True),
        sa.Column("application_url", sa.String(length=2048), nullable=True),
        sa.Column("fee_summary", sa.String(length=300), nullable=True),
        sa.Column("processing_time_summary", sa.String(length=300), nullable=True),
        sa.Column("validity_summary", sa.String(length=300), nullable=True),
        sa.Column("renewal_summary", sa.String(length=300), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="document_publication_status"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["states.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_civic_documents_category"), "civic_documents", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_civic_documents_department_id"), "civic_documents", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_civic_documents_district_id"), "civic_documents", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_civic_documents_document_type"), "civic_documents", ["document_type"], unique=False
    )
    op.create_index(op.f("ix_civic_documents_locale"), "civic_documents", ["locale"], unique=False)
    op.create_index(
        op.f("ix_civic_documents_organization_id"),
        "civic_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_civic_documents_publication_status"),
        "civic_documents",
        ["publication_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_civic_documents_service_id"), "civic_documents", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_civic_documents_slug"), "civic_documents", ["slug"], unique=True)
    op.create_index(
        op.f("ix_civic_documents_source_id"), "civic_documents", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_civic_documents_state_id"), "civic_documents", ["state_id"], unique=False
    )
    op.create_index(op.f("ix_civic_documents_status"), "civic_documents", ["status"], unique=False)
    op.create_index(
        op.f("ix_civic_documents_verification_status"),
        "civic_documents",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "document_application_methods",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel_type",
            postgresql.ENUM(
                "ONLINE",
                "OFFLINE",
                "MOBILE_APP",
                "MEESEVA",
                "DEPARTMENT_PORTAL",
                "SERVICE_CENTER",
                "IN_PERSON",
                "OTHER",
                name="application_channel_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["civic_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_application_methods_document_id"),
        "document_application_methods",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_requirements",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "requirement_type",
            postgresql.ENUM(
                "AGE",
                "RESIDENCY",
                "INCOME",
                "OCCUPATION",
                "OTHER",
                name="requirement_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_value", sa.Integer(), nullable=True),
        sa.Column("max_value", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["civic_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_requirements_document_id"),
        "document_requirements",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_supporting_documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("civic_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["civic_document_id"], ["civic_documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["civic_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_supporting_documents_civic_document_id"),
        "document_supporting_documents",
        ["civic_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_supporting_documents_document_id"),
        "document_supporting_documents",
        ["document_id"],
        unique=False,
    )
    op.add_column(
        "scheme_required_documents", sa.Column("civic_document_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_scheme_required_documents_civic_document_id"),
        "scheme_required_documents",
        ["civic_document_id"],
        unique=False,
    )
    op.create_foreign_key(
        "scheme_required_documents_civic_document_id_fkey",
        "scheme_required_documents",
        "civic_documents",
        ["civic_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "service_required_documents", sa.Column("civic_document_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_service_required_documents_civic_document_id"),
        "service_required_documents",
        ["civic_document_id"],
        unique=False,
    )
    op.create_foreign_key(
        "service_required_documents_civic_document_id_fkey",
        "service_required_documents",
        "civic_documents",
        ["civic_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "service_required_documents_civic_document_id_fkey",
        "service_required_documents",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_service_required_documents_civic_document_id"),
        table_name="service_required_documents",
    )
    op.drop_column("service_required_documents", "civic_document_id")
    op.drop_constraint(
        "scheme_required_documents_civic_document_id_fkey",
        "scheme_required_documents",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_scheme_required_documents_civic_document_id"),
        table_name="scheme_required_documents",
    )
    op.drop_column("scheme_required_documents", "civic_document_id")
    op.drop_index(
        op.f("ix_document_supporting_documents_document_id"),
        table_name="document_supporting_documents",
    )
    op.drop_index(
        op.f("ix_document_supporting_documents_civic_document_id"),
        table_name="document_supporting_documents",
    )
    op.drop_table("document_supporting_documents")
    op.drop_index(op.f("ix_document_requirements_document_id"), table_name="document_requirements")
    op.drop_table("document_requirements")
    op.drop_index(
        op.f("ix_document_application_methods_document_id"),
        table_name="document_application_methods",
    )
    op.drop_table("document_application_methods")
    op.drop_index(op.f("ix_civic_documents_verification_status"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_status"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_state_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_source_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_slug"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_service_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_publication_status"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_organization_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_locale"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_document_type"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_district_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_department_id"), table_name="civic_documents")
    op.drop_index(op.f("ix_civic_documents_category"), table_name="civic_documents")
    op.drop_table("civic_documents")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see f36a332eb8ca's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. Only the enums *first created*
    # here are dropped — `delivery_mode`/`verification_status`/
    # `application_channel_type`/`requirement_type` are reused via
    # `postgresql.ENUM(..., create_type=False)` above and must not be
    # dropped while Services'/Schemes' tables still reference them.
    for enum_name in ("document_publication_status", "document_category", "document_type"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
