"""add_ai_knowledge_chunks

Revision ID: a17cd12b571d
Revises: cea938af5888
Create Date: 2026-09-28 14:24:31.759598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a17cd12b571d"
down_revision: str | Sequence[str] | None = "cea938af5888"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_knowledge_chunks",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "array_length(embedding, 1) = embedding_dimensions",
            name="ck_ai_knowledge_chunks_embedding_length_matches_dimensions",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "locale",
            "chunk_index",
            name="uq_ai_knowledge_chunks_entity_locale_chunk",
        ),
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_content_hash"),
        "ai_knowledge_chunks",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_embedding_model"),
        "ai_knowledge_chunks",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_entity_id"), "ai_knowledge_chunks", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_entity_type"),
        "ai_knowledge_chunks",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_locale"), "ai_knowledge_chunks", ["locale"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_knowledge_chunks_locale"), table_name="ai_knowledge_chunks")
    op.drop_index(op.f("ix_ai_knowledge_chunks_entity_type"), table_name="ai_knowledge_chunks")
    op.drop_index(op.f("ix_ai_knowledge_chunks_entity_id"), table_name="ai_knowledge_chunks")
    op.drop_index(op.f("ix_ai_knowledge_chunks_embedding_model"), table_name="ai_knowledge_chunks")
    op.drop_index(op.f("ix_ai_knowledge_chunks_content_hash"), table_name="ai_knowledge_chunks")
    op.drop_table("ai_knowledge_chunks")
    # ### end Alembic commands ###
