"""add_auth_tracking_notifications

Revision ID: bd7be548b0ad
Revises: a17cd12b571d
Create Date: 2026-09-28 15:51:53.324142

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd7be548b0ad"
down_revision: str | Sequence[str] | None = "a17cd12b571d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "DEADLINE_REMINDER",
                "CHANGE_DETECTED",
                "ENTITY_NO_LONGER_AVAILABLE",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("change_record_id", sa.UUID(), nullable=True),
        sa.Column("dedup_key", sa.String(length=300), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["change_record_id"], ["change_records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedup_key", name="uq_notifications_user_dedup_key"),
    )
    op.create_index(
        op.f("ix_notifications_entity_id"), "notifications", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_entity_type"), "notifications", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "notification_delivery_attempts",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Enum("IN_APP", "EMAIL", name="delivery_channel"), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "SENT", "FAILED", name="delivery_status"), nullable=False
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_delivery_attempts_notification_id"),
        "notification_delivery_attempts",
        ["notification_id"],
        unique=False,
    )
    op.create_table(
        "tracked_items",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("scheme_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(job_id, service_id, scheme_id, document_id) = 1",
            name="ck_tracked_items_exactly_one_entity",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["civic_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "job_id",
            "service_id",
            "scheme_id",
            "document_id",
            name="uq_tracked_items_user_entity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_tracked_items_document_id"), "tracked_items", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_tracked_items_job_id"), "tracked_items", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_tracked_items_scheme_id"), "tracked_items", ["scheme_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_items_service_id"), "tracked_items", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_tracked_items_user_id"), "tracked_items", ["user_id"], unique=False)
    op.add_column("users", sa.Column("email_notifications_enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_notifications_enabled")
    op.drop_index(op.f("ix_tracked_items_user_id"), table_name="tracked_items")
    op.drop_index(op.f("ix_tracked_items_service_id"), table_name="tracked_items")
    op.drop_index(op.f("ix_tracked_items_scheme_id"), table_name="tracked_items")
    op.drop_index(op.f("ix_tracked_items_job_id"), table_name="tracked_items")
    op.drop_index(op.f("ix_tracked_items_document_id"), table_name="tracked_items")
    op.drop_table("tracked_items")
    op.drop_index(
        op.f("ix_notification_delivery_attempts_notification_id"),
        table_name="notification_delivery_attempts",
    )
    op.drop_table("notification_delivery_attempts")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_entity_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_entity_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 8b03ffd6bc96's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. All three enums here were first
    # created by this migration, so all three are dropped.
    for enum_name in ("delivery_status", "delivery_channel", "notification_type"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
