"""add_eligibility_domain

Revision ID: cea938af5888
Revises: 9ae6dce71bfa
Create Date: 2026-09-28 13:07:27.613738

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea938af5888"
down_revision: str | Sequence[str] | None = "9ae6dce71bfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_rules",
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("scheme_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="eligibility_rule_publication_status"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "NEEDS_REVIEW",
                "EXPIRED",
                "UNVERIFIED",
                name="verification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(job_id, scheme_id, service_id) = 1",
            name="ck_eligibility_rules_exactly_one_entity",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eligibility_rules_job_id"), "eligibility_rules", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_rules_publication_status"),
        "eligibility_rules",
        ["publication_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eligibility_rules_scheme_id"), "eligibility_rules", ["scheme_id"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_rules_service_id"), "eligibility_rules", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_rules_source_id"), "eligibility_rules", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_rules_verification_status"),
        "eligibility_rules",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "eligibility_conditions",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column(
            "attribute",
            sa.Enum(
                "AGE",
                "INCOME_ANNUAL",
                "EDUCATION_LEVEL",
                "ACADEMIC_PERCENTAGE",
                "ACADEMIC_CGPA",
                "RESIDENCE_STATE",
                "CATEGORY",
                name="eligibility_attribute",
            ),
            nullable=False,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "EQ", "NEQ", "GTE", "LTE", "BETWEEN", "IN", "NOT_IN", name="eligibility_operator"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("numeric_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("numeric_value_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("text_value", sa.String(length=200), nullable=True),
        sa.Column("text_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "numeric_value IS NOT NULL OR text_value IS NOT NULL OR text_values IS NOT NULL",
            name="ck_eligibility_conditions_has_a_value",
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["eligibility_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eligibility_conditions_rule_id"),
        "eligibility_conditions",
        ["rule_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eligibility_conditions_rule_id"), table_name="eligibility_conditions")
    op.drop_table("eligibility_conditions")
    op.drop_index(op.f("ix_eligibility_rules_verification_status"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_source_id"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_service_id"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_scheme_id"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_publication_status"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_job_id"), table_name="eligibility_rules")
    op.drop_table("eligibility_rules")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 8b03ffd6bc96's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. All three enums here were first
    # created by this migration (unlike `verification_status`, reused via
    # `create_type=False` above), so all three are dropped.
    for enum_name in (
        "eligibility_operator",
        "eligibility_attribute",
        "eligibility_rule_publication_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
