"""add scholarship details

Revision ID: f36a332eb8ca
Revises: 8b03ffd6bc96
Create Date: 2026-09-22 16:49:22.746378

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f36a332eb8ca"
down_revision: str | Sequence[str] | None = "8b03ffd6bc96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scholarship_details",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column(
            "education_level",
            sa.Enum(
                "SCHOOL",
                "INTERMEDIATE",
                "DIPLOMA",
                "UNDERGRADUATE",
                "POSTGRADUATE",
                "DOCTORAL",
                "PROFESSIONAL",
                "VOCATIONAL",
                "OTHER",
                name="education_level",
            ),
            nullable=True,
        ),
        sa.Column("course_discipline", sa.String(length=300), nullable=True),
        sa.Column("institution_type", sa.String(length=150), nullable=True),
        sa.Column(
            "study_mode",
            sa.Enum("FULL_TIME", "PART_TIME", "DISTANCE", "ONLINE", "OTHER", name="study_mode"),
            nullable=True,
        ),
        sa.Column("year_of_study", sa.String(length=100), nullable=True),
        sa.Column("minimum_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("minimum_cgpa", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("academic_requirement_notes", sa.Text(), nullable=True),
        sa.Column("application_opens", sa.Date(), nullable=True),
        sa.Column("application_closes", sa.Date(), nullable=True),
        sa.Column("correction_window_end", sa.Date(), nullable=True),
        sa.Column("academic_year", sa.String(length=20), nullable=True),
        sa.Column("renewable", sa.Boolean(), nullable=False),
        sa.Column("renewal_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scheme_id"], ["schemes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scholarship_details_scheme_id"), "scholarship_details", ["scheme_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scholarship_details_scheme_id"), table_name="scholarship_details")
    op.drop_table("scholarship_details")
    # ### end Alembic commands ###

    # Not auto-generated, and necessary (see 8b03ffd6bc96's downgrade()
    # for the precedent): Alembic's autogenerate creates a native
    # Postgres ENUM TYPE alongside a column using sa.Enum(...), but
    # doesn't emit a matching DROP TYPE. Both enums here were first
    # created by this migration (no other table references them), so
    # both are dropped.
    for enum_name in ("study_mode", "education_level"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
